### PR TITLE
Fix a bug and add sorting to stl files

### PR DESCRIPTION
**Pull request by eyal0**
There is a bug in the code where it should say "read_binary..." and not "parse_binary..."

Also, I added sorting into the Solid type.  OpenScad output is not deterministic: the output can have facets in a different order each time.  This sort normalizes an STL file to a single order.

### CODE REVIEW

**Comment by Gjacquenot** [comment]
I have merged your commits in master, and this branch is in the pull request stream of main project apparentlymart/python-stl: your commits broke the automatic running [tests](https://travis-ci.org/apparentlymart/python-stl/jobs/126679815)

```
Installed /home/travis/build/apparentlymart/python-stl/.eggs/coverage-4.1b2-py3.4-linux-x86_64.egg

................F.....

======================================================================

FAIL: test_pep8_conformance (test_code_style.TestCodeStyle)
```

@eyal0 : Could you propose new commit to fix this? Please run tests before submitting new pull request. Thanks

**Comment by eyal0** [comment]
python3 setup.py test passed on my computer!  Maybe it is a different pep8?  Anyway, I had left the print statements that do not need to be there so I deleted them.

**Comment by Gjacquenot** [comment]
Thanks a lot @eyal0

**Comment by eyal0** [comment]
Glad to help!  My first pull request!

**Pull request merged**
